apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Update to where the Llama Stack deployment is running
namespace: llama-stack
resources:
- sa.yaml
- clusterrole.yaml
- otel-collector-llamastack-sidecar.yaml
