# Once this exists, any pod with the template.metadata.annotation below will send traces to otel-collector sidecar container:
# sidecar.opentelemetry.io/inject: llamastack-otelsidecar
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: llamastack-otelsidecar
spec:
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  config:
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    exporters:
      debug:
        verbosity: basic
      # Export the dev tenant traces to a Tempo instance
      otlphttp/dev:
        # This assumes a TempoStack in the same namespace as Llama Stack exists
        endpoint: https://tempo-tempostack-gateway:8080/api/traces/v1/dev
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: "dev"

    processors: {}

    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    service:
      extensions:
      - bearertokenauth
      pipelines:
        traces:
          exporters:
          - debug
          - otlphttp/dev
          receivers:
          - otlp
      telemetry:
        metrics:
          address: '0.0.0.0:8888'
  mode: sidecar
