apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llama-stack
resources:
- tempo-role.yaml
- minio-secret-tempo.yaml
- minio-user-creds.yaml
- minio-tempo-pvc.yaml
- minio-tempo-svc.yaml
- minio-tempo.yaml
- tempo-multitenant.yaml
