apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: prometheus
    access: proxy
    editable: true
    type: prometheus
    url: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"
    isDefault: true
    secureJsonData:
      "httpHeaderValue1": "Bearer ${token}"
    jsonData:
      "httpHeaderName1": "Authorization"
      "timeInterval": "5s"
      "tlsSkipVerify": true
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: "grafana-sa-token"
          key: "token"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: tempo
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana   # This label matches the grafana Grafana instance
  datasource:
    name: tempo
    access: proxy
    editable: true
    type: tempo
    # This is specific to "llama-stack" namespace. If running tempostack elsewhere, need to update
    url: "https://tempo-tempostack-gateway.llama-stack.svc.cluster.local:8081/api/traces/v1/dev/tempo"
    isDefault: false
    secureJsonData:
      "httpHeaderValue1": "Bearer ${token}"
    jsonData:
      "httpHeaderName1": "Authorization"
      "timeInterval": "5s"
      "tlsSkipVerify": true
  valuesFrom:
    - targetPath: "secureJsonData.httpHeaderValue1"
      valueFrom:
        secretKeyRef:
          name: "grafana-sa-token"
          key: "token"
