apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-extract
spec:
  template:
    spec:
      containers:
      - name: extract
        image: registry.access.redhat.com/ubi9/ubi
        command: ["sh", "-c"]
        args:
        - |
          echo "Packing reports...";
          cd /output && \
          tar czf guidellm-reports.tgz *.yaml
        volumeMounts:
        - name: output
          mountPath: /output
      restartPolicy: Never
      volumes:
      - name: output
        persistentVolumeClaim:
          claimName: guidellm-output-pvc
