apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: grafana
spec:
  config:
    log:
      level: warn
      mode: console
    security:
      admin_password: "admin"
      admin_user: "admin"
  dashboardLabelSelector:
    - matchExpressions:
        - key: dashboards
          operator: In
          values:
            - grafana
